### ISSUE TITLE
Make images link to the section as well. 

### ISSUE THREAD

**Issue by ghost** [GalileyGalileo/Material-You-app-list#11]
For reddit, YouTube, mastodon, pixiv and uuuuuhhh.. other social media apps (I forgot lmao) which have a custom image, tapping the image will only open the image link. This can be annoying, say if you misclick. (As I do, **very frequently**) There is a way to fix this A.K.A making the image also take you to their sections.

Markdown images:

`[![Image Name](image-link)](#section-link)`

HTML images:

`<a href="#section-link"><img src="image-link"></a>`

**Comment by TeaOwO** [comment]
Video reference:

https://github.com/GalileyGalileo/Material-You-app-list/assets/123305689/31900db1-6b6b-43bc-b08a-ea5847019592

**Comment by GalileyGalileo** [comment]
Fixed) Thanks for advise.
